### ISSUE TITLE
Hardcoded IP address

### ISSUE THREAD

**Issue by TheVexy** [Codemonkey1973/OCC#4]
If the IP addresses are hardcoded in the place where ORLACO_bInit is called, then the function will always try to initialize a connection to those specific IP addresse 

In main.c L 96 : 
`ORLACO_bInit(&sInstance.sOrlaco, "192.168.2.10", "192.168.2.255", ORLACO_DEFAULT_PORT);`

A more flexible design would be to retrieve the IP addresses from a configuration file or command line arguments. This would allow you to change the IP addresses without modifying and recompiling the code.

**Comment by biwiki** [comment]
There is already a command option for users to specify the camera's IP address:
```
-i --ip <IP>:<port>              Set the IP address and port of the camera, e.g. 192.168.2.1:17215
```

**Comment by TheVexy** [comment]
> There is already a command option for users to specify the camera's IP address:
> 
> ```
> -i --ip <IP>:<port>              Set the IP address and port of the camera, e.g. 192.168.2.1:17215
> ```

I understand now, but why the need for the 2 hardcoded addresses ?

**Comment by biwiki** [comment]
We would need to initialize the stack with default values, these can be overwritten by command line arguments before they are actual used. 
Curious to know if this cause can you any issues?

**Comment by Codemonkey1973** [comment]
Hi,
 Sorry for the delay in looking at this, currently a bit snowed under with
work so will take a look as soon as possible.

Regards,

Lee

**Comment by Codemonkey1973** [comment]
Hi All,

 Finally had an opportunity to look at this. Those IP's are just defaults for the unicast and broadcast addresses. Both of them can already be overridden.

-d or --discover sets the broadcast IP and port (the hardcoded 192.168.2.255)
-i or --ip sets the unicast IP and port (the hardcoded 192.168.2.1)

Sorry, its a whiile since I wrote this and i've done a lot of other stuff since so kind of forgot how it all worked!

I think that 192.168.2.x may have been the default network prefix for the cameras when factory new, so that is why they were chosen.

Regards,

Lee
